import { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import api from '../api'
import styles from '../styles/Home.module.css'
import { Flight } from '../types'

type Props = {
  origins: Flight["origin"][]
}
export const getStaticProps: GetStaticProps<Props> = async () => {
  const origins = await api.origin.list()
  return {
    props: {
      origins
    }
  }
}

export default function Home({ origins }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a <a href="https://flybondi.com/ar">Flybondi!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {origins.map(origin => (
            <Link key={origin} href={`/${origin}`} className={styles.card}>
              <h2>{origin} &rarr;</h2>
            </Link>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
